
apiVersion: v2
name: infra-helm
description: A Helm chart for Kubernetes

type: application

version: 1.1.0

appVersion: 1.1.0

dependencies:
  # - name: kafka
  #   version: x.x.x
  #   repository: "https://ricardo-aires.github.io/helm-charts"

  - name: elasticsearch
    version: x.x.x
    repository: "https://charts.bitnami.com/bitnami"
    
  - name: metrics-server
    version: x.x.x
    repository: "https://charts.bitnami.com/bitnami"

  - name: kube-prometheus-stack
    version: x.x.x
    repository: "https://prometheus-community.github.io/helm-charts"


