---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-admin
    namespace: kube-system

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: jenkins-admin
# rules:
#   - apiGroups: [""]
#     resources: ["*"]
#     verbs: ["*"]
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: jenkins-admin
#   namespace: apps
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: jenkins-admin
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: jenkins-admin
# subjects:
# - kind: ServiceAccount
#   name: jenkins-admin
#   namespace: apps



# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#     name: jenkins-agent
#     namespace: apps
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/exec"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/log"]
#   verbs: ["get","list","watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#     name: jenkins-agent
#     namespace: apps
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: jenkins-agent
# subjects:
# - kind: ServiceAccount
#   name: jenkins-agent
#   namespace: apps
